name: Sync To Gitee
on:
# 如果需要PR触发把push前的#去掉
  push:
  schedule:
    # 每天北京时间9点跑
    - cron:  '0 1 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:ygguorun/scoop-bucket.git"
          destination-repo: "git@gitee.com:ladengweisi/scoop-bucket.git"
